# Generated by Django 3.1.6 on 2023-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20230117_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='./placeholder.jpg', null=True, upload_to='./', verbose_name='Image'),
        ),
    ]
