# Generated by Django 3.1.6 on 2023-01-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20230117_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='./placeholder.png', null=True, upload_to='./', verbose_name='Image'),
        ),
    ]
